apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ly6st4zvy-go
  janus-idp.io/tekton: ly6st4zvy-go
  backstage.io/kubernetes-id: ly6st4zvy-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ly6st4zvy-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
